# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Devolutions.RemoteDesktopManagerAgent
PackageVersion: 2025.1.30.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
Protocols:
- rdp
- powershell
FileExtensions:
- rdm
ProductCode: '{255193AD-3119-419C-8410-A31F68C41A87}'
ReleaseDate: 2025-04-09
AppsAndFeaturesEntries:
- UpgradeCode: '{D3ECDF42-9073-4760-94D5-73F8D2AFDF8A}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerAgent.2025.1.30.0.msi
  InstallerSha256: 6355AA608333292D50E838004745B3609DE78761061047E81ED5BC11D705EB01
ManifestType: installer
ManifestVersion: 1.6.0

