# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Devolutions.RemoteDesktopManagerAgent
PackageVersion: 2024.2.15.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
Protocols:
- rdp
- powershell
FileExtensions:
- rdm
ProductCode: '{49B3273D-A00B-4BBF-BC8C-0E43EE3906B1}'
ReleaseDate: 2024-07-12
AppsAndFeaturesEntries:
- UpgradeCode: '{D3ECDF42-9073-4760-94D5-73F8D2AFDF8A}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerAgent.2024.2.15.0.msi
  InstallerSha256: 4C719D5291011A0DEDAA54C32C1FD6DDA4D84B41D6BF04C9F860D50C73F2EAFA
ManifestType: installer
ManifestVersion: 1.6.0

