# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Devolutions.Workspace
PackageVersion: 2025.1.3.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- credential
- http
- https
ProductCode: '{347598B2-9FD1-4C0D-A591-340703F116D0}'
ReleaseDate: 2025-04-08
AppsAndFeaturesEntries:
- UpgradeCode: '{EA58A259-5C39-43E8-9183-EAAB09293D3F}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Devolutions.Workspace-2025.1.3.0-x64.msi
  InstallerSha256: EE9EF5877079642DE5B08D6B637F649A54D1F80124A5B3DC47F41E64C5BD7820
ManifestType: installer
ManifestVersion: 1.6.0

