# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Devolutions.RemoteDesktopManager
PackageVersion: 2026.2.20.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
Protocols:
- rdp
FileExtensions:
- csv
- psafe3
- rde
- rdg
- rdm
- rdp
- vnc
- vrb
- vrd
- vre
- xml
ProductCode: '{671C23BF-B992-422B-8009-9DB674A2BD2E}'
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- UpgradeCode: '{2707F3BF-4D7B-40C2-882F-14B0ED869EE8}'
Installers:
- Architecture: neutral
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.2026.2.20.0.msi
  InstallerSha256: F4D3C09754780B85E0FADCD65A636781596DA3228C02EB09BC58FE0A6CC2CAB4

- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.win-x64.2026.2.20.0.msi
  InstallerSha256: 8512D82785A899DFA3FF1E9BF971734A9B35A845612A49276DA30CDEE77223F8

- Architecture: arm64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.win-arm64.2026.2.20.0.msi
  InstallerSha256: C656EA69384F65CBF183FC8BDE57391CF467BF06C14D3DBB3FAF2B6856A193C8
ManifestType: installer
ManifestVersion: 1.12.0

