# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Devolutions.RemoteDesktopManagerAgent
PackageVersion: 2025.3.20.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
Protocols:
- rdp
- powershell
FileExtensions:
- rdm
ProductCode: '{064DAABC-F0E5-42EC-AA5D-1DD253F08E03}'
ReleaseDate: 2025-10-24
AppsAndFeaturesEntries:
- UpgradeCode: '{D3ECDF42-9073-4760-94D5-73F8D2AFDF8A}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerJump.2025.3.20.0.msi
  InstallerSha256: <sha256>
ManifestType: installer
ManifestVersion: 1.10.0

