# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Devolutions.Launcher
PackageVersion: 2025.3.17.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
Protocols:
- rdp
- ssh
- vnc
- telnet
- http
- https
- ftp
- sftp
- ard
- webdav
ProductCode: '{A6CC4B4B-9B34-410C-AAFE-6CD5706BD94D}'
ReleaseDate: 2025-10-20
AppsAndFeaturesEntries:
- UpgradeCode: '{CB5FC4EF-9B66-411D-8F6E-2713D2B8F664}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.Devolutions.Launcher.2025.3.17.0.msi
  InstallerSha256: <sha256>
ManifestType: installer
ManifestVersion: 1.10.0

