# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Devolutions.Launcher
PackageVersion: 2025.1.30.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
Protocols:
- rdp
- ssh
- vnc
- telnet
- http
- https
- ftp
- sftp
- ard
- webdav
ProductCode: '{5F95E58F-FA1D-4113-97C1-B7DF5845BA65}'
ReleaseDate: 2025-04-09
AppsAndFeaturesEntries:
- UpgradeCode: '{CB5FC4EF-9B66-411D-8F6E-2713D2B8F664}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.Devolutions.Launcher.2025.1.30.0.msi
  InstallerSha256: D9D50A13B49C0D6B8B01F3FBBA0A99C9399748DF0D9FE5F014F2C6D6366BBDF6
ManifestType: installer
ManifestVersion: 1.6.0

