# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Devolutions.RemoteDesktopManager
PackageVersion: 2024.1.14.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- rdp
FileExtensions:
- csv
- psafe3
- rde
- rdg
- rdm
- rdp
- vnc
- vrb
- vrd
- vre
- xml
ProductCode: '{42360679-513F-407B-B0CC-A3C84F2A8E59}'
ReleaseDate: 2024-03-07
AppsAndFeaturesEntries:
- UpgradeCode: '{2707F3BF-4D7B-40C2-882F-14B0ED869EE8}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.2024.1.14.0.msi
  InstallerSha256: 5B0581B858998F13A42874DE97717F2752A46F65089BF038D56E3B0782C412FB
ManifestType: installer
ManifestVersion: 1.6.0

